version: "2"
services:
  frontend-booking:
    restart: always
    build:
      context: .
      args:
        - SERVER_IP=${SERVER_IP}    
    ports:
      - "8011:80"
    networks:
      - backend_network
networks:
  backend_network:
    external: true